# 开发环境配置
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://124.222.225.172:3306/miracle_agility?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# JWT配置 - 开发环境
jwt:
  secret: miracle_agility_dev_jwt_secret_2024
  access-token-expiration: 86400 # 开发环境延长到24小时
  refresh-token-expiration: 604800 # 7天

# 日志配置 - 开发环境
logging:
  level:
    com.miracle.agility: DEBUG
    org.springframework.web: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

file:
  upload:
    path: ./data/uploads/        # 文件上传目录（相对于后端项目根目录）
  access:
    domain: http://localhost:8085   # 文件访问域名